server:
  port: 8080

guns:
  swagger-open: true              #是否开启swagger (true/false)
  kaptcha-open: false             #是否开启登录时验证码 (true/false)
#  file-upload-path: d:/tmp       #文件上传目录(不配置的话为java.io.tmpdir目录)
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

spring:
  profiles:
    active: @spring.active@
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: com.stylefeng.guns.modular.system.model

log:
  path: guns-logs

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://192.168.0.203:3306/bdp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: bdp
    password: bdp
    db-name: bdp #用来搜集数据库的所有表
    filters: wall,mergeStat
  jenkins:
      url: http://192.168.0.204:8080
      user: rest_api
      token: rest_api
      rest_url: http://192.168.0.203:8080
  hive:
      beeline: /bin/beeline -n hdfs -p hdfs -u
      url: jdbc:hive2://bdata003:10000/
  bdpjob:
      jobconfig: /bdp/jobconfig
      joblib: /bdp/sparkLib
      zkurl: 192.168.0.193,192.168.0.194,192.168.0.195:2180
      namenodestr: 192.168.0.193:8020,192.168.0.194:8020

#多数据源情况的配置
guns:
  muti-datasource:
    open: false
    url: jdbc:mysql://192.168.0.203:3306/bdp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: bdp
    password: bdp
    dataSourceNames:
      - dataSourceGuns
      - dataSourceBiz

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.0.203:3306/bdp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: bdp
    password: bdp
    db-name: bdp #用来搜集数据库的所有表
    filters: wall,mergeStat
  jenkins:
      url: http://192.168.0.204:8080
      user: rest_api
      token: rest_api
      rest_url: http://192.168.0.203:8080
  hive:
      beeline: /bin/beeline -n hdfs -p hdfs -u
      url: jdbc:hive2://bdata003:10000/
  bdpjob:
      jobconfig: /bdp/jobconfig
      joblib: /bdp/sparkLib
      zkurl: 192.168.0.193,192.168.0.194,192.168.0.195:2180
      namenodestr: 192.168.0.193:8020,192.168.0.194:8020
---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.0.203:3306/bdp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: bdp
    password: bdp
    filters: wall,mergeStat
  jenkins:
      url: http://192.168.0.204:8080
      user: rest_api
      token: rest_api
      rest_url: http://192.168.0.203:8080
  hive:
      beeline: /bin/beeline -n hdfs -p hdfs -u
      url: jdbc:hive2://bdata003:10000/
  bdpjob:
      jobconfig: /bdp/jobconfig
      joblib: /bdp/sparkLib
      zkurl: 192.168.0.193,192.168.0.194,192.168.0.195:2180
      namenodestr: 192.168.0.193:8020,192.168.0.194:8020




---

spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://192.168.0.203:3306/bdp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
      username: bdp
      password: bdp
      filters: wall,mergeStat
  jenkins:
      url: http://192.168.0.204:8080
      user: rest_api
      token: rest_api
      rest_url: http://192.168.0.203:8080
  hive:
      beeline: /bin/beeline -n hdfs -p hdfs -u
      url: jdbc:hive2://bdata003:10000/
  bdpjob:
      jobconfig: /bdp/jobconfig
      joblib: /bdp/sparkLib
      zkurl: 192.168.0.193,192.168.0.194,192.168.0.195:2180
      namenodestr: 192.168.0.193:8020,192.168.0.194:8020